#!/usr/bin/env bash

apt-get update && \
	apt-get install -y build-essential && \
    # apt-get install -y libprotobuf-dev protobuf-compiler && \
    apt-get install -y cmake && \
    apt-get install -y git