#!/bin/bash

libjpeg_version=8.4.0
export CURR_DIR=$(pwd)
jpeg_dir="$CURR_DIR/vendor/jpeg"
jpeg_lib_dir="$CURR_DIR/vendor/jpeg/lib"

git_url="https://github.com/stohrendorf/libjpeg-cmake.git libjpeg-$libjpeg_version"

rm -rf $jpeg_dir/*
mkdir -p $jpeg_dir && cd $jpeg_dir
git clone $git_url
cd libjpeg*

mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=$jpeg_dir \
    -DCMAKE_BUILD_TYPE="Release" \
    -DBUILD_SHARED_LIBS=ON  ../

make
make install

