#!/bin/bash

libtesseract_version=4.1.3
export CURR_DIR=$(pwd)
tesseract_dir="$CURR_DIR/vendor/tesseract"
tesseract_lib_dir="$CURR_DIR/vendor/tesseract/lib"

git_url="https://github.com/tesseract-ocr/tesseract.git libtesseract-$libtesseract_version"

rm -rf $tesseract_dir/*
mkdir -p $tesseract_dir && cd $tesseract_dir
git clone $git_url
git checkout tags/$libtesseract_version
cd libtesseract*

# https://docs.opencv.org/3.4/db/d4c/tutorial_install_tesseract.html

leptonica_dir="$CURR_DIR/vendor/leptonica/lib/cmake/leptonica"

mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=$tesseract_dir \
    -DCMAKE_BUILD_TYPE="Release" \
    -DLeptonica_DIR=$leptonica_dir -DBUILD_TRAINING_TOOLS=OFF \
    -DBUILD_SHARED_LIBS=ON  ../

make
make install