#!/bin/bash

libwebp_version=1.2.1
export CURR_DIR=$(pwd)
webp_install_dir="$CURR_DIR/vendor/webp"

download_url="https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-$libwebp_version.tar.gz"

rm -rf $webp_install_dir/*
mkdir -p $webp_install_dir && cd $webp_install_dir
curl -L $download_url | tar -zxf-
cd libwebp*

./configure \
    --prefix=$webp_install_dir \
    --disable-static \
    --enable-shared \
    --enable-swap-16bit-csp

make
make install