#!/bin/bash

zlib_version=1.2.11
export CURR_DIR=$(pwd)
zlib_dir="$CURR_DIR/vendor/zlib"
zlib_lib_dir="$CURR_DIR/vendor/zlib/lib"

download_url="https://github.com/madler/zlib/archive/refs/tags/v$zlib_version.tar.gz"
# git_url="https://github.com/madler/zlib.git zlib-$zlib_version"

rm -rf $zlib_dir/*
mkdir -p $zlib_dir && cd $zlib_dir
# git clone $git_url
curl -L $download_url | tar -zxf-
cd zlib*

mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=$zlib_dir \
    -DCMAKE_BUILD_TYPE="Release" \
    -DBUILD_SHARED_LIBS=ON  ../

make
make install
